/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opalvoip.opal;

public class OpalMiscellaneous {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OpalMiscellaneous(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OpalMiscellaneous obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OPALJNI.delete_OpalMiscellaneous(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setProtocol(String value) {
    OPALJNI.OpalMiscellaneous_protocol_set(swigCPtr, this, value);
  }

  public String getProtocol() {
    return OPALJNI.OpalMiscellaneous_protocol_get(swigCPtr, this);
  }

  public void setCallToken(String value) {
    OPALJNI.OpalMiscellaneous_callToken_set(swigCPtr, this, value);
  }

  public String getCallToken() {
    return OPALJNI.OpalMiscellaneous_callToken_get(swigCPtr, this);
  }

  public void setIdentifier(String value) {
    OPALJNI.OpalMiscellaneous_identifier_set(swigCPtr, this, value);
  }

  public String getIdentifier() {
    return OPALJNI.OpalMiscellaneous_identifier_get(swigCPtr, this);
  }

  public void setPayload(SWIGTYPE_p_void value) {
    OPALJNI.OpalMiscellaneous_payload_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getPayload() {
    long cPtr = OPALJNI.OpalMiscellaneous_payload_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setSize(long value) {
    OPALJNI.OpalMiscellaneous_size_set(swigCPtr, this, value);
  }

  public long getSize() {
    return OPALJNI.OpalMiscellaneous_size_get(swigCPtr, this);
  }

  public OpalMiscellaneous() {
    this(OPALJNI.new_OpalMiscellaneous(), true);
  }

}
